export const NOTI_ASYM = {
  INVALID_GAME_NAME: 'Game name is invalid!',
  INVALID_GOLD_COINS_BET_VALUES: 'Gold coin bet values are invalid!',
  INVALID_SWEEP_COINS_BET_VALUES: 'Sweep coin bet values are invalid!',
  INVALID_ROW_COUNTS: 'Row counts are invalid!',
  INVALID_ASYMMETRIC_CHANGE: 'Asymmetric chance is invalid!',
  INVALID_GAME_ID: 'Game ID is invalid!',
  INVALID_SYMBOL_NAME: 'Symbol name is invalid!',
  INVALID_MINIMUM_PAYLINE: 'Minimum payline is invalid!',
  INVALID_CHANCE_RATIO: 'Chance ratio is invalid!',
  INVALID_SYMBOL_VALUES: 'Symbol values is invalid!',
  INVALID_IS_WILD: 'Wild is invalid!',
  INVALID_IS_JACKPOT: 'Jackpot is invalid!',
  INVALID_IS_SCATTER: 'Scatter is invalid!',
  INVALID_USER: 'User is invalid!',
  INVALID_ROW_INDEX: 'Row index are invalid!',
  INVALID_PAYLINE_ID: 'Payline ID is invalid!',
  INVALID_BET_VALUE: 'Bet value is invalid!',
  INVALID_PAYLINE_ID_LIST: 'Payline Ids are invalid!',
  INVALID_CURRENCY: 'Currency is invalid!',
  INVALID_SCATTER_PRIZE_ID: 'Scatter prize Id is invalid!',
  INVALID_FREE_SPINS: 'Free spins are invalid!',
  INVALID_FREE_SPINS_MULTIPLIER: 'Free spins multiplier is invalid!',
  INVALID_PRIZE: 'Prize is invalid!',
  INVALID_CURRENT_SPIN_MULTIPLIER: 'Current spin multiplier is invalid!',

  ERROR_NO_GAME: 'No game existed!',
  ERROR_NO_GAME_OR_BET_AVAILABLE: 'No game or bet available existed!',
  ERROR_EXISTED_GAME_NAME: 'Game name is existed!',
  ERROR_CREATE_GAME: 'Create new game failed!',
  ERROR_UPDATE_GAME: 'Update game failed!',
  ERROR_EXISTED_SYMBOL_NAME: 'Symbol name is existed!',
  ERROR_ADD_SYMBOL: 'Add new symbol failed!',
  ERROR_UPDATE_SYMBOL: 'Update symbol failed!',
  ERROR_NO_SYMBOL: 'No symbol existed!',
  ERROR_SET_BET: 'Set bet failed!',
  ERROR_SELECT_PAYLINE: 'Select payline failed!',
  ERROR_CREATE_PAYLINE: 'Create payline failed!',
  ERROR_CREATE_PAYLINE_EXISTED: 'Payline is existed!',
  ERROR_REMOVE_PAYLINE: 'Remove payline failed!',
  ERROR_GAME_PROGRESS_EXISTED: 'Game progress is existed!',
  ERROR_GET_SETTINGS: 'Get settings failed!',

  NOT_FOUND_GAME_PROGRESS: 'Game progress not found!',
}

export const ERROR_NAME_ASYM = {
  INVALID_GAME_NAME: 'InvalidGameName',
  INVALID_GOLD_COINS_BET_VALUES: 'InvalidGoldCoinsBetValues',
  INVALID_SWEEP_COINS_BET_VALUES: 'InvalidSweepCoinsBetValues',
  INVALID_ROW_COUNTS: 'InvalidRowCounts',
  INVALID_ASYMMETRIC_CHANGE: 'InvalidAsymmetricChance',
  INVALID_GAME_ID: 'InvalidGameId',
  INVALID_SYMBOL_NAME: 'InvalidSymbolName',
  INVALID_MINIMUM_PAYLINE: 'InvalidMinimumPayline',
  INVALID_CHANCE_RATIO: 'InvalidChanceRatio',
  INVALID_SYMBOL_VALUES: 'InvalidSymbolValues',
  INVALID_IS_WILD: 'InvalidWild',
  INVALID_IS_JACKPOT: 'InvalidJackpot',
  INVALID_IS_SCATTER: 'InvalidScatter',
  INVALID_USER: 'InvalidUser',
  INVALID_ROW_INDEX: 'InvalidRowIndex',
  INVALID_PAYLINE_ID: 'InvalidPaylineId',
  INVALID_BET_VALUE: 'InvalidBetValue',
  INVALID_PAYLINE_ID_LIST: 'InvalidPaylineId',
  INVALID_CURRENCY: 'InvalidCurrency',
  INVALID_SCATTER_PRIZE_ID: 'InvalidScatterPrizeId',
  INVALID_FREE_SPINS: 'InvalidFreeSpins',
  INVALID_FREE_SPINS_MULTIPLIER: 'InvalidFreeSpinsMultiplier',
  INVALID_PRIZE: 'InvalidPrize',
  INVALID_CURRENT_SPIN_MULTIPLIER: 'InvalidCurrentSpinMultiplier',

  ERROR_NO_GAME: 'ErrorNoGame',
  ERROR_NO_GAME_OR_BET_AVAILABLE: 'ErrorNoGameOrBetAvailable',
  ERROR_EXISTED_GAME_NAME: 'ErrorExistedGameName',
  ERROR_CREATE_GAME: 'ErrorCreateGame',
  ERROR_UPDATE_GAME: 'ErrorUpdateGame',
  ERROR_EXISTED_SYMBOL_NAME: 'ErrorExistedSymbolName',
  ERROR_ADD_SYMBOL: 'ErrorAddSymbol',
  ERROR_UPDATE_SYMBOL: 'ErrorUpdateSymbol',
  ERROR_NO_SYMBOL: 'ErrorNoSymbol',
  ERROR_SET_BET: 'ErrorSetBet',
  ERROR_SELECT_PAYLINE: 'ErrorSelectPayline',
  ERROR_CREATE_PAYLINE: 'ErrorCreatePayline',
  ERROR_CREATE_PAYLINE_EXISTED: 'ErrorCreatePaylineExisted',
  ERROR_REMOVE_PAYLINE: 'ErrorRemovePayline',
  ERROR_GAME_PROGRESS_EXISTED: 'ErrorGameProgressExisted',
  ERROR_GET_SETTINGS: 'ErrorGetSettings',

  NOT_FOUND_GAME_PROGRESS: 'NotFoundGameProgress'
}
