// source: games/slotsgames/accumulate_multiplier_slots_game.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.schema.AccumulateMultiplierSlotsGameModel', null, global);
goog.exportSymbol('proto.schema.CreateAccumulateMultiplierSlotsGameRequest', null, global);
goog.exportSymbol('proto.schema.UpdateAccumulateMultiplierSlotsGameRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schema.AccumulateMultiplierSlotsGameModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.schema.AccumulateMultiplierSlotsGameModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schema.AccumulateMultiplierSlotsGameModel.displayName = 'proto.schema.AccumulateMultiplierSlotsGameModel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.schema.CreateAccumulateMultiplierSlotsGameRequest.repeatedFields_, null);
};
goog.inherits(proto.schema.CreateAccumulateMultiplierSlotsGameRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schema.CreateAccumulateMultiplierSlotsGameRequest.displayName = 'proto.schema.CreateAccumulateMultiplierSlotsGameRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.repeatedFields_, null);
};
goog.inherits(proto.schema.UpdateAccumulateMultiplierSlotsGameRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.displayName = 'proto.schema.UpdateAccumulateMultiplierSlotsGameRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schema.AccumulateMultiplierSlotsGameModel.prototype.toObject = function(opt_includeInstance) {
  return proto.schema.AccumulateMultiplierSlotsGameModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schema.AccumulateMultiplierSlotsGameModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.AccumulateMultiplierSlotsGameModel.toObject = function(includeInstance, msg) {
  var f, obj = {
    maxMultiplier: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schema.AccumulateMultiplierSlotsGameModel}
 */
proto.schema.AccumulateMultiplierSlotsGameModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schema.AccumulateMultiplierSlotsGameModel;
  return proto.schema.AccumulateMultiplierSlotsGameModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schema.AccumulateMultiplierSlotsGameModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schema.AccumulateMultiplierSlotsGameModel}
 */
proto.schema.AccumulateMultiplierSlotsGameModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMaxMultiplier(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schema.AccumulateMultiplierSlotsGameModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schema.AccumulateMultiplierSlotsGameModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schema.AccumulateMultiplierSlotsGameModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.AccumulateMultiplierSlotsGameModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaxMultiplier();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
};


/**
 * optional double max_multiplier = 1;
 * @return {number}
 */
proto.schema.AccumulateMultiplierSlotsGameModel.prototype.getMaxMultiplier = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.schema.AccumulateMultiplierSlotsGameModel} returns this
 */
proto.schema.AccumulateMultiplierSlotsGameModel.prototype.setMaxMultiplier = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.schema.CreateAccumulateMultiplierSlotsGameRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    gameName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    availableGoldCoinsBetValuesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
    availableSweepCoinsBetValuesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    rowCountsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    maxMultiplier: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schema.CreateAccumulateMultiplierSlotsGameRequest;
  return proto.schema.CreateAccumulateMultiplierSlotsGameRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGameName(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addAvailableGoldCoinsBetValues(values[i]);
      }
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addAvailableSweepCoinsBetValues(values[i]);
      }
      break;
    case 4:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRowCounts(values[i]);
      }
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMaxMultiplier(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schema.CreateAccumulateMultiplierSlotsGameRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGameName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAvailableGoldCoinsBetValuesList();
  if (f.length > 0) {
    writer.writePackedDouble(
      2,
      f
    );
  }
  f = message.getAvailableSweepCoinsBetValuesList();
  if (f.length > 0) {
    writer.writePackedDouble(
      3,
      f
    );
  }
  f = message.getRowCountsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      4,
      f
    );
  }
  f = message.getMaxMultiplier();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
};


/**
 * optional string game_name = 1;
 * @return {string}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.getGameName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.setGameName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated double available_gold_coins_bet_values = 2;
 * @return {!Array<number>}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.getAvailableGoldCoinsBetValuesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.setAvailableGoldCoinsBetValuesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.addAvailableGoldCoinsBetValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.clearAvailableGoldCoinsBetValuesList = function() {
  return this.setAvailableGoldCoinsBetValuesList([]);
};


/**
 * repeated double available_sweep_coins_bet_values = 3;
 * @return {!Array<number>}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.getAvailableSweepCoinsBetValuesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.setAvailableSweepCoinsBetValuesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.addAvailableSweepCoinsBetValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.clearAvailableSweepCoinsBetValuesList = function() {
  return this.setAvailableSweepCoinsBetValuesList([]);
};


/**
 * repeated int32 row_counts = 4;
 * @return {!Array<number>}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.getRowCountsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.setRowCountsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.addRowCounts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.clearRowCountsList = function() {
  return this.setRowCountsList([]);
};


/**
 * optional double max_multiplier = 5;
 * @return {number}
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.getMaxMultiplier = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.schema.CreateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.CreateAccumulateMultiplierSlotsGameRequest.prototype.setMaxMultiplier = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.repeatedFields_ = [3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    gameId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    gameName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    availableGoldCoinsBetValuesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    availableSweepCoinsBetValuesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 4)) == null ? undefined : f,
    rowCountsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    maxMultiplier: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schema.UpdateAccumulateMultiplierSlotsGameRequest;
  return proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGameId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGameName(value);
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addAvailableGoldCoinsBetValues(values[i]);
      }
      break;
    case 4:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addAvailableSweepCoinsBetValues(values[i]);
      }
      break;
    case 5:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRowCounts(values[i]);
      }
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMaxMultiplier(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGameId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGameName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAvailableGoldCoinsBetValuesList();
  if (f.length > 0) {
    writer.writePackedDouble(
      3,
      f
    );
  }
  f = message.getAvailableSweepCoinsBetValuesList();
  if (f.length > 0) {
    writer.writePackedDouble(
      4,
      f
    );
  }
  f = message.getRowCountsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      5,
      f
    );
  }
  f = message.getMaxMultiplier();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
};


/**
 * optional string game_id = 1;
 * @return {string}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.getGameId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.setGameId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string game_name = 2;
 * @return {string}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.getGameName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.setGameName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated double available_gold_coins_bet_values = 3;
 * @return {!Array<number>}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.getAvailableGoldCoinsBetValuesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.setAvailableGoldCoinsBetValuesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.addAvailableGoldCoinsBetValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.clearAvailableGoldCoinsBetValuesList = function() {
  return this.setAvailableGoldCoinsBetValuesList([]);
};


/**
 * repeated double available_sweep_coins_bet_values = 4;
 * @return {!Array<number>}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.getAvailableSweepCoinsBetValuesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.setAvailableSweepCoinsBetValuesList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.addAvailableSweepCoinsBetValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.clearAvailableSweepCoinsBetValuesList = function() {
  return this.setAvailableSweepCoinsBetValuesList([]);
};


/**
 * repeated int32 row_counts = 5;
 * @return {!Array<number>}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.getRowCountsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.setRowCountsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.addRowCounts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.clearRowCountsList = function() {
  return this.setRowCountsList([]);
};


/**
 * optional double max_multiplier = 6;
 * @return {number}
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.getMaxMultiplier = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.schema.UpdateAccumulateMultiplierSlotsGameRequest} returns this
 */
proto.schema.UpdateAccumulateMultiplierSlotsGameRequest.prototype.setMaxMultiplier = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


goog.object.extend(exports, proto.schema);
